runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: tb5FSx50PBU0wYODDqz/dEa/meRMmCejSQ2SP2eEbBg=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie